<?php

namespace Sf\QuranBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdhkarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextAdhkarCategoryRepository extends EntityRepository
{
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        $orderByOrdering = array('name' => 'ASC');
        $orderBy = $orderBy == null ? $orderByOrdering : array_merge($orderBy, $orderByOrdering);
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

}
